Repository pygae/galgebra, pull requests merged in 2020-04, with the labels that each got.

#232 Add CI for python 3.8
  .circleci/config.yml
  galgebra/deprecated.py
  galgebra/lt.py
  setup.py
Labels: soft CI failure

#231 Improve errors in dop constructors
  galgebra/dop.py
  galgebra/mv.py
  test/test_differential_ops.py
Labels: component: differential operators, enhancement

#235 Cherry-pick comments from @abrombo's branch
  galgebra/ga.py
  galgebra/metric.py
  galgebra/mv.py
Labels: component: docs

#236 Remove more special cases for scalars
  galgebra/ga.py
Labels: soft CI failure

#63 Include the scalar element in the list of blades and bases
  doc/changelog.rst
  examples/Terminal/coefs_test.py
  examples/ipython/Terminal.ipynb
  galgebra/ga.py
  galgebra/mv.py
  test/test_test.py
Labels: soft CI failure

#230 Fix Operator Table in Documentation
  doc/galgebra.md
  doc/galgebra_guide.ipynb
Labels: bug, component: docs

#241 Fix easy issues with flake8
  galgebra/deprecated.py
  galgebra/dop.py
  galgebra/ga.py
  galgebra/lt.py
  galgebra/metric.py
  galgebra/mv.py
  galgebra/printer.py
  setup.cfg
Labels: soft CI failure

#240 Bump sphinx to 3.0
  doc/conf.py
  doc/readthedocs-pip-requirements.txt
Labels: component: docs

#242 Tidy redundant tuple parentheses and bad comma spacing
  galgebra/deprecated.py
  galgebra/dop.py
  galgebra/ga.py
  galgebra/lt.py
  galgebra/metric.py
  galgebra/mv.py
  galgebra/printer.py
  setup.cfg
  test/test_lt.py
  test/test_mv.py
  test/test_test.py
Labels: soft CI failure

#246 Make blade_superscripts a GradedTuple too
  galgebra/ga.py
Labels: soft CI failure

#245 Deprecate a bunch of similar members of `Ga`
  doc/changelog.rst
  galgebra/ga.py
  galgebra/lt.py
  test/test_test.py
Labels: Deprecation

#243 Add support for passing other forms of argument to `Mv.subs`
  galgebra/mv.py
  test/test_mv.py
Labels: enhancement

#248 Deprecate more useless attributes of `Ga`
  doc/changelog.rst
  galgebra/ga.py
  test/test_test.py
Labels: Deprecation

#250 Avoid injecting a float into a sympy expression
  galgebra/metric.py
  test/test_mv.py
Labels: bug

#253 Fix OrderedBiMap so that it works in annotations
  galgebra/_backports/__init__.py
  galgebra/_backports/typing.py
  galgebra/ga.py
  test/test_misc.py
Labels: bug

#254 Show member documentation in source order
  doc/conf.py
Labels: component: docs

#255 Remove `Ga.deriv` which is undocumented and unused
  galgebra/ga.py
Labels: soft CI failure

#260 Ensure the latex printer is not invoked when the string printer is requested
  galgebra/mv.py
  test/test_printer.py
Labels: bug, component: printer

#264 Fix some more str / latex mixups in the printer
  examples/ipython/Old Format.ipynb
  examples/ipython/Terminal.ipynb
  galgebra/dop.py
  galgebra/lt.py
  galgebra/mv.py
  galgebra/printer.py
  test/test_test.py
Labels: bug, component: printer

#258 Do not clobber sympy.Basic.__str__
  examples/ipython/LaTeX.ipynb
  examples/ipython/Terminal.ipynb
  examples/ipython/dop.ipynb
  examples/ipython/inner_product.ipynb
  galgebra/printer.py
  test/test_printer.py
Labels: bug, component: printer
